# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ClimateControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('value_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('value_max', models.DecimalField(decimal_places=2, max_digits=8)),
                ('device_state', models.BooleanField(default=False)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Climate')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('start_hour', models.TimeField()),
                ('stop_hour', models.TimeField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interface.Device')),
            ],
        ),
        migrations.AddField(
            model_name='climatecontrol',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Device'),
        ),
    ]
