# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Device')),
            ],
        ),
        migrations.AlterField(
            model_name='climatecontrol',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='devicetimer',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
