# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20160710_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatealert',
            name='climate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interface.Climate'),
        ),
    ]
