# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20160710_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatealert',
            name='value_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='climatealert',
            name='value_min',
            field=models.IntegerField(default=0),
        ),
    ]
