# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20160710_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatealert',
            name='value_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='climatealert',
            name='value_min',
            field=models.IntegerField(null=True),
        ),
    ]
