# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_auto_20160710_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'OFF'), (1, 'ON'), (2, 'AUTO'), (3, 'ERROR')]),
        ),
    ]
