# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20160717_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='pin',
            field=models.PositiveSmallIntegerField(choices=[(7, 7), (11, 11), (12, 12), (13, 13), (15, 15), (16, 16), (18, 18), (22, 22), (29, 29), (31, 31), (32, 32), (33, 33), (35, 35), (36, 36), (37, 37), (38, 38), (40, 40)], default=7),
            preserve_default=False,
        ),
    ]
