# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_device_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='climate',
            name='pin',
            field=models.PositiveSmallIntegerField(default=40),
        ),
    ]
