# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_auto_20160724_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatecontrol',
            name='value_max',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='climatecontrol',
            name='value_min',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
