# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_auto_20160724_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatecontrol',
            name='value_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='climatecontrol',
            name='value_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
