# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_auto_20160730_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[('off', 'off'), ('on', 'on'), ('auto', 'auto'), ('ERROR', 'ERROR')]),
        ),
    ]
