# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_auto_20160730_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.CharField(choices=[('off', 'off'), ('on', 'on'), ('auto', 'auto'), ('ERROR', 'ERROR')], max_length=5),
        ),
    ]
